apiVersion: v2
name: coturn
description: A Helm chart for coturn https://github.com/coturn/coturn

type: application
version: 0.1.0
appVersion: 1.0.0

dependencies:
- name: common
  version: 0.1.0
  repository: file://../common