apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blue-strims-gg
  namespace: strims
spec:
  secretName: blue-strims-gg-tls
  issuerRef:
    name: letsencrypt-strims
    kind: ClusterIssuer
  dnsNames:
  - '*.blue.strims.gg'
  - blue.strims.gg
