apiVersion: apps/v1
kind: Deployment
metadata:
  name: stun
  namespace: strims
  labels:
    strims.gg/stun: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      strims.gg/stun: "true"
  template:
    metadata:
      labels:
        strims.gg/stun: "true"
    spec:
      restartPolicy: Always
      containers:
      - name: coturn
        image: coturn/coturn:4.5
        args:
          - --stun-only
        readinessProbe:
          tcpSocket:
            port: 3478
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 3478
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: stun
  namespace: strims
  labels:
    strims.gg/stun: "true"
spec:
  type: NodePort
  ports:
    - port: 3478
      targetPort: 3478
      protocol: UDP
  selector:
    strims.gg/stun: "true"
