apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: strims
  name: svc-invites
  labels:
    strims.gg/svc: leader
spec:
  replicas: 1
  selector:
    matchLabels:
      strims.gg/svc: leader
  template:
    metadata:
      labels:
        strims.gg/svc: leader
    spec:
      serviceAccountName: node-reader
      nodeSelector:
        strims.gg/svc: leader
      containers:
      - name: strims
        image: ghcr.io/memelabs/strims/svc:latest
        imagePullPolicy: Always
        args: ["serve-invites", "-config", "/etc/strims/config.yaml"]
        ports:
        - name: metrics
          containerPort: 1971
        - name: debug
          containerPort: 6060
        - name: http
          containerPort: 10080
        volumeMounts:
        - name: config-vol
          mountPath: /etc/strims
      volumes:
      - name: config-vol
        configMap:
          name: svc-invites-config
---
apiVersion: v1
kind: Service
metadata:
  name: svc-invites
  namespace: strims
spec:
  type: NodePort
  selector:
    strims.gg/svc: leader
  ports:
    - protocol: TCP
      nodePort: 31315
      port: 80
      targetPort: http
