metrics:
  address: "0.0.0.0:1971"
debug:
  address: "0.0.0.0:6060"
storage:
  adapter: "postgres"
  postgres:
    connStr: "user=strims password=password host=postgresql.strims.svc.cluster.local sslmode=disable database=strims"
    enableLogging: false
http:
  address: "0.0.0.0:10080"
