metrics:
  address: "0.0.0.0:1971"
debug:
  address: "0.0.0.0:6060"
storage:
  adapter: "postgres"
  postgres:
    connStr: "user=strims password=password host=postgresql.strims.svc.cluster.local sslmode=disable database=strims"
queue:
  adapter: "postgres"
  postgres:
    connStr: "user=strims password=password host=postgresql.strims.svc.cluster.local sslmode=disable database=strims"
session:
  remote:
    enabled: true
  headless: []
vnic:
  webrtc:
    enabled: true
    tcpMuxAddress: 0.0.0.0:5000
    udpMuxAddress: 0.0.0.0:5000
  websocket:
    enabled: true
