output              = "../internal/models"
wipe                = true
no-hooks            = true
add-global-variants = true
struct-tag-casing   = "camel"

[psql]
host    = "localhost"
dbname  = "strims"
user    = "strims"
pass    = "strims"
sslmode = "disable"

[sqlite3]
dbname = "./dev.sqlite"

[aliases.tables.nodes.columns]
cpus = "CPUs"
region_lng = "RegionLng"
sku_name = "SKUName"
sku_network_cap = "SKUNetworkCap"
sku_network_speed = "SKUNetworkSpeed"
sku_price_monthly = "SKUPriceMonthly"
sku_price_hourly = "SKUPriceHourly"
