{{- define "common.deployment-mountedSecrets-volume" -}}
{{- if .Values.mountedSecrets }}
  {{- range $key, $value := .Values.mountedSecrets }}
        - name: {{ lower $key }}
          secret:
            secretName: {{ $value.secretName }}
            items:
            {{- range $key, $value := $value.items }}
            - key: {{ $value.key }}
              path: {{ $value.path }}
            {{- end }}
  {{- end }}
{{- end }}
{{- end -}}
