{{- define "common.deployment-mountedSecrets-volumeMount" -}}
{{- if .Values.mountedSecrets }}
  {{- range $key, $value := .Values.mountedSecrets }}
          - name: {{ lower $key }}
            mountPath: {{ $value.mountPath }}
  {{- end }}
{{- end }}
{{- end -}}
