{{- define "common.service" -}}
{{- if .Values.service.enabled }}
---
apiVersion: v1
kind: Service
{{ template "common.service-metadata" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
{{- if .Values.service.ports }}
  ports:
  {{- range $key, $value := .Values.service.ports }}
    - name: {{ $key }}
      protocol: {{ $value.protocol }}
      port: {{ $value.port }}
      targetPort: {{ $value.port }}
  {{- end }}
{{- end }}
{{- end }}
{{- end -}}
