metrics:
  address: "0.0.0.0:1971"
debug:
  address: "0.0.0.0:6060"
storage:
  adapter: "postgres"
  bbolt:
    path: "hack/svc/.strims"
  postgres:
    connStr: "user=postgres password=supersecret host=172.17.0.2 sslmode=disable database=strims"
http:
  address: "0.0.0.0:8083"
  tls:
    cert: "hack/tls/development.crt"
    key: "hack/tls/development.key"
session:
  remote:
    enabled: true
  headless:
    - id: 55708340105248770
      key: "gbnFAhEj/oTc4MCZ+qW/m8NHDV3+3lZf1TuVThZzDj8="
vnic:
  # label: ""
  webrtc:
    enabled: true
    tcpMuxAddress: 0.0.0.0:5000
    udpMuxAddress: 0.0.0.0:5000
  websocket:
    enabled: true
