metrics:
  address: "0.0.0.0:1971"
debug:
  address: "0.0.0.0:6060"
storage:
  adapter: "bbolt"
  bbolt:
    path: "hack/svc/.strims"
http:
  address: "0.0.0.0:8083"
  tls:
    cert: "hack/tls/development.crt"
    key: "hack/tls/development.key"
session:
  remote:
    enabled: true
  headless:
vnic:
  webrtc:
    enabled: true
    tcpMuxAddress: 0.0.0.0:5000
    udpMuxAddress: 0.0.0.0:5000
  websocket:
    enabled: true
