replicas: 1

resources: {
  "requests":
  {"memory":"128Mi", "cpu":"100m"},
  "limits":
  {"memory":"1024Mi", "cpu":"500m"}
  }

persistence:
  enabled: true
  storageClassName: local-path
  size: 10Gi

config:
    schema_config:
      configs:
      - from: 2018-04-15
        store: boltdb
        object_store: filesystem
        schema: v9
        index:
          prefix: index_
          period: 168h

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h #7 day retention period

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - controller      