package: services
interfaces:
    -
      name: Service
      methods:
      -
        name: CreateNetwork
        type: unary
        input: 'r *CreateNetworkRequest'
        output: '*CreateNetworkResponse'
      -
        name: UpdateNetwork
        type: unary
        input: 'r *UpdateNetworkRequest'
        output: '*UpdateNetworkResponse'
      -
        name: DeleteNetwork
        type: unary
        input: 'r *DeleteNetworkRequest'
        output: '*DeleteNetworkResponse'
      -
        name: GetNetwork
        type: unary
        input: 'r *GetNetworkRequest'
        output: '*GetNetworkResponse'
      -
        name: GetNetworks
        type: unary
        input: 'r *GetNetworksRequest'
        output: '*GetNetworksResponse'
      -
        name: JoinSwarm
        type: unary
        input: 'r *JoinSwarmRequest'
        output: '*JoinSwarmResponse'
      -
        name: LeaveSwarm
        type: unary
        input: 'r *LeaveSwarmRequest'
        output: '*LeaveSwarmResponse'
      -
        name: StartHLSIngress
        type: unary
        input: 'r *StartHLSIngressRequest'
        output: '*StartHLSIngressResponse'
      -
        name: StartHLSEgress
        type: unary
        input: 'r *StartHLSEgressRequest'
        output: '*StartHLSEgressResponse'
      -
        name: StopHLSEgress
        type: unary
        input: 'r *StopHLSEgressRequest'
        output: '*StopHLSEgressResponse'
      -
        name: GetIngressStreams
        type: unary
        input: 'r *GetIngressStreamsRequest'
        output: '*GetIngressStreamsResponse'
