package: services
interfaces:
    - 
      name: Service 
      methods:
      -
        name: JoinSwarm
        type: unary
        input: 'r *JoinSwarmRequest'
        output: '*JoinSwarmResponse'
      -
        name: LeaveSwarm
        type: unary
        input: 'r *LeaveSwarmRequest'
        output: '*LeaveSwarmResponse'
      -
        name: StartHLSIngress
        type: unary
        input: 'r *StartHLSIngressRequest'
        output: '*StartHLSIngressResponse'
      -
        name: StartHLSEgress
        type: unary
        input: 'r *StartHLSEgressRequest'
        output: '*StartHLSEgressResponse'
      -
        name: StopHLSEgress
        type: unary
        input: 'r *StopHLSEgressRequest'
        output: '*StopHLSEgressResponse'
      -
        name: GetIngressStreams
        type: unary
        input: 'r *GetIngressStreamsRequest'
        output: '*GetIngressStreamsResponse'
