name: Lint and build android app
on:
  push:
    paths:
      - 'android/**'

jobs:
  main:
    name: Test & Build Debug
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/jbpratt/gomobile-android/gomobile-android:latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Go bridge
        run: |
          go mod download
          gomobile init
          mkdir ./android/app/libs
          gomobile bind -o ./android/app/libs/bridge.aar -target=android ./android/bridge
      - name: Unit tests
        working-directory: ./android
        run: bash ./gradlew lint
      - name: Build Debug APK
        working-directory: ./android
        run: bash ./gradlew assembleDebug --stacktrace
