name: lint and build android app
on:
  pull_request:
    paths:
      - '.github/workflows/android-ci.yaml'
      - 'android/**'
  push:
    branches:
      - main
    paths:
      - 'android/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: android/app/libs/bridge.aar
          key: ${{ runner.os }}-${{ hashFiles('android/bridge/*') }}
      - name: Install Dependencies
        working-directory: ./android
        run: gem install bundler && bundle install
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Build Go bridge
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          go get golang.org/x/mobile/cmd/gomobile
          go mod download
          gomobile init
          mkdir ./android/app/libs
          gomobile bind -o ./android/app/libs/bridge.aar -target=android ./android/bridge
      - name: Fastlane build
        working-directory: ./android
        run: fastlane build
