name: Lint and build android app
on:
  push:
    paths:
      - 'android/**'

jobs:
  main:
    name: Test & Build Debug
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        working-directory: ./android
        run: bash ./gradlew lint

      - name: Build Debug APK
        working-directory: ./android
        run: bash ./gradlew assembleDebug --stacktrace
