name: Lint and build android app
on:
  pull_request:
    paths:
      - 'android/**'
  push:
    branches:
      - master
    paths:
      - 'android/**'

jobs:
  main:
    name: Lint & Build Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - name: Install NDK
        env:
          ANDROID_BUILD_TOOLS_VERSION: 27.0.3
          ANDROID_PLATFORM_VERSION: "android-28"
        run: |
          echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager "platform-tools"
          echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION"
          echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager "platforms;$ANDROID_PLATFORM_VERSION"
          echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager "ndk-bundle"
      - name: Build Go bridge
        run: |
          go get golang.org/x/mobile/cmd/gomobile
          go mod download
          gomobile init
          mkdir ./android/app/libs
          gomobile bind -o ./android/app/libs/bridge.aar -target=android ./android/bridge
      - name: Lint
        working-directory: ./android
        run: bash ./gradlew lint
      - name: Build Debug APK
        working-directory: ./android
        run: bash ./gradlew assembleDebug --stacktrace
