name: atmon-build

on:
  push:
    paths:
      - '.github/workflows/atmon-build.yaml'
      - 'infra/cmd/atmon/**'
      - 'go.mod'
      - 'go.sum'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Docker login
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: docker login https://ghcr.io -u ${username} -p ${password}
    - name: Build image
      run: |
        docker build \
          -t ghcr.io/memelabs/strims/atmon:latest \
          --build-arg "GIT_SHA=$GITHUB_SHA" \
          --build-arg "BUILD_DATE=$(date)" \
          -f infra/cmd/atmon/Dockerfile .

    - name: Publish image
      run: docker push ghcr.io/memelabs/strims/atmon:latest
