name: build base ffmpeg image

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/ffmpeg.yaml'
      - 'hack/ffmpeg/ffmpeg.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: distroless/actions/apko-publish@main
        with:
          config: hack/ffmpeg/ffmpeg.yaml
          tag: ghcr.io/memelabs/strims/ffmpeg:latest
