name: nginx

on:
  push:
    branches: [ 'main' ]
    paths:
      - '.github/workflows/nginx.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: nginxinc/docker-nginx
        # TODO: use latest stable version once module support is released
        ref: master
    - name: Docker login
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: docker login https://ghcr.io -u ${username} -p ${password}
    - name: Build image
      run: docker build -f modules/Dockerfile.alpine --build-arg ENABLED_MODULES="brotli" -t ghcr.io/memelabs/strims/nginx:latest .
    - name: Publish image
      run: docker push ghcr.io/memelabs/strims/nginx:latest
