name: svc-cd

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/svc-cd.yaml'
      - 'go.mod'
      - 'go.sum'
      - 'cmd/svc/**'
      - 'pkg/**'
      - 'internal/**'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: cmd/svc/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/memelabs/strims/svc:latest
