name: svc-ci

on:
  pull_request:
    paths:
      - '.github/workflows/svc-ci.yaml'
      - 'go.mod'
      - 'go.sum'
      - 'cmd/svc/**'
      - 'pkg/**'
      - 'internal/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build image
      run: docker build -f cmd/svc/Dockerfile . -t ghcr.io/memelabs/strims/svc:latest
