name: web-cd

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Docker login
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: docker login https://docker.pkg.github.com -u ${username} -p ${password}
    - name: Build image
      run: docker build -f hack/web/Dockerfile . -t docker.pkg.github.com/memelabs/strims/web:latest
    - name: Publish image
      run: docker push docker.pkg.github.com/memelabs/strims/web:latest
